[package]
name = "rust_egg"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["staticlib", "cdylib"]

[dependencies]
ocaml = "0.22.4"
egg = "0.9.2"
itertools = "0.10"
symbolic_expressions = "5.0.3"
lazy_static = "1.4.0"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"